/// Flutter icons FoodIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FoodIcon
///      fonts:
///       - asset: fonts/FoodIcon.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FoodIcon {
  FoodIcon._();

  static const _kFontFam = 'FoodIcon';
  static const String _kFontPkg = null;

  static const IconData ramen = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grape = IconData(0xf785, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza = IconData(0xf818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
